# Generated by Django 4.0.5 on 2023-09-01 14:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_borrowed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device.device')),
                ('brand', models.CharField(max_length=100)),
                ('ram', models.IntegerField(default=1)),
                ('rom', models.IntegerField(default=1)),
            ],
            bases=('device.device',),
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device.device')),
                ('brand', models.CharField(max_length=100)),
            ],
            bases=('device.device',),
        ),
    ]
