# Generated by Django 4.0.5 on 2023-09-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='brand',
        ),
        migrations.AddField(
            model_name='device',
            name='brand',
            field=models.CharField(default='Samsung', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobile',
            name='camera',
            field=models.IntegerField(default=10),
        ),
    ]
