# Generated by Django 4.0.5 on 2023-09-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='devices',
            field=models.ManyToManyField(blank=True, null=True, to='device.device'),
        ),
    ]
