# Generated by Django 4.0.5 on 2023-09-01 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_employee_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='devices',
        ),
    ]
