# Generated by Django 4.0.5 on 2023-09-01 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_remove_laptop_brand_remove_mobile_brand_device_brand_and_more'),
        ('company', '0005_devicelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelog',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.device'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.employee'),
        ),
    ]
